services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD
      - ACCEPT_EULA="Y"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped
  backend:
    image: gitlab.dit.htwk-leipzig.de:5050/projekt2024-s-audit-tool/backend:latest
    environment:
      - SPRING_APPLICATION_NAME
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
      - SPRING_JPA_HIBERNATE_DDL_AUTO
      - CORS_URLS
    ports:
      - "8081:81"
    entrypoint: ["java", "-jar","/app/insight-spring.jar"]
    restart: unless-stopped

volumes:
  mssql_data: